COUNTRIES = [
    ('US', 'United States'),
    ('GB', 'United Kingdom'),
    ('CA', 'Canada'),
    ('AU', 'Australia'),
    ('DE', 'Germany'),
    ('FR', 'France'),
    ('JP', 'Japan'),
    ('CN', 'China'),
    ('IN', 'India'),
    ('BR', 'Brazil'),
    ('MX', 'Mexico'),
    ('ZA', 'South Africa'),
    ('NG', 'Nigeria'),
    ('KE', 'Kenya'),
    ('EG', 'Egypt'),
    ('AE', 'United Arab Emirates'),
    ('SG', 'Singapore'),
    ('HK', 'Hong Kong'),
    ('CH', 'Switzerland'),
    ('NL', 'Netherlands'),
]
