# Generated by Django 4.2.28 on 2026-04-06 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'REJECTED'), ('EXPIRED', 'Expired')], default='NOT_STARTED', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('review_started_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kyc', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Verification',
                'verbose_name_plural': 'KYC Verifications',
                'db_table': 'account_kyc',
            },
        ),
        migrations.AddField(
            model_name='usermetadata',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='KYCFailedAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('DIVERS_LICENSE', "Driver's License"), ('SELFIE', 'Selfie with ID')], max_length=20)),
                ('failure_reason', models.CharField(max_length=50)),
                ('failure_details', models.TextField(blank=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_failed_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Failed Attempt',
                'verbose_name_plural': 'KYC Failed Attempts',
                'db_table': 'accounts_kyc_failed_attempt',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('DIVERS_LICENSE', "Driver's_License"), ('SELFIE', 'Self with ID')], max_length=20)),
                ('file', models.FileField(upload_to='kyc_documents/%y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, choices=[('BLURRY', 'Image is blurry or unclear'), ('WRONG_FORMAT', 'Wrong file format'), ('FILE_TOO_LARGE', 'File size exceeds limit'), ('EXPIRED', 'Document is expired'), ('NAME_MISMATCH', 'Name does not match account'), ('ADDRESS_MISMATCH', 'Address does not match'), ('SELFIE_MISMATCH', 'Selfie does not match ID photo'), ('INCOMPLETE', 'Incomplete document'), ('OTHER', 'Other reason')], max_length=50, null=True)),
                ('rejection_details', models.TextField(blank=True, help_text='Additional details about rejection')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('KYC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.kyc')),
            ],
            options={
                'verbose_name': 'KYC Document',
                'verbose_name_plural': 'KYC Documents',
                'db_table': 'accounts_kyc_document',
                'unique_together': {('KYC', 'document_type', 'status')},
            },
        ),
    ]
