# Generated by Django 4.2.28 on 2026-04-07 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_kyc_usermetadata_last_activity_kycfailedattempt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kycdocument',
            old_name='KYC',
            new_name='kyc',
        ),
        migrations.AlterUniqueTogether(
            name='kycdocument',
            unique_together={('kyc', 'document_type', 'status')},
        ),
    ]
